name: Generate Mandelbrot Set Image

on:
  push:
    branches:
      - develop

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install packages
        run: |
          apt update
          apt install -y dos2unix
          dos2unix ./run.sh
          chmod +x ./run.sh
          apt update && apt install -y build-essential libpng-dev libgmp-dev
          apt install -y ffmpeg m4 m4-doc
      - name: Adjust EOL
        run: dos2unix ./run.sh
      - name: Run Script
        run: ./run.sh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-run
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
